### ISSUE TITLE
Post shoot stats

### ISSUE THREAD

**Issue by quii** [quii/vue-fast#151]
We can use maths to give some encouragement

> If you tidied up the worst 5% of your shots, you could've scored a B3

> If you tidied up the worst 5% of your shots, you could've beaten your PB

**Comment by quii** [comment]
Due to @LoganHeasman200 's change, PBs are conceptually the same as classifications, which works nicely for the above. There is no need for different code paths, etc. 

Rough logic
- If game state is completed
- Calculate the 95th percentile arrow score. 
- If you multiply above by arrows in the round and >= first classification _not_ achieved, display some message

**Comment by areon546** [comment]
Could also have a way of seeing what the expected score would be if you completed a round if you decided to not score the rest of a round for a rough estimate. I mark these by just having the unscored arrows as misses.

**Comment by quii** [comment]
![CleanShot 2024-12-20 at 16 13 51](https://github.com/user-attachments/assets/c6ba3ebf-cc86-4409-ab4f-c62c6af19593)
