### ISSUE TITLE
Add signatures to scores

### ISSUE THREAD

**Issue by areon546** [quii/vue-fast#155]
Add optional boxes for signatures so that Fast could be better used as evidence for a score (informally)

**Comment by areon546** [comment]
Conceptually I think it would be clean to add to the history section, but I expect that the History section is static stuff and may cause problems as I imagine it's stored in some static way. 

Alternatively optional boxes below the box where you select a round from would also be clean.

**Comment by quii** [comment]
@LoganHeasman200 had a decent idea that instead of adding this, we instead make it so you can save the score to PDF. Then people can use their device's software to sign the PDF. That'll be simpler to implement

**Comment by quii** [comment]
[portsmouth-2024-11-21.pdf](https://github.com/user-attachments/files/17940274/portsmouth-2024-11-21.pdf)

Gave it a punt, it's a bit rough, but kinda works! 

1. Go to user details and put your name in (so the form can fill it in)
2. Go to history -> pick a score
3. Press the button
4. Clumsily try and sign a PDF on your phone

**Comment by LoganHeasman200** [comment]
It seems to work for me, however one thing to note, is that when I click the download button I'm switched from dark mode into light mode

![Screenshot_20241127_215456_Chrome.jpg](https://github.com/user-attachments/assets/05929601-62ac-4f42-8d5f-d0cf869dc8fa)

![Screenshot_20241127_215450_Chrome.jpg](https://github.com/user-attachments/assets/7dffe72a-0a98-4648-88f3-a0fad288e52d)

**Comment by quii** [comment]
Do you mean the app stays in light mode? That's uh, fun. I had to do it for the PDF because well, it doesn't make sense to have a dark PDF I don't think. 

I have a feeling this is to do with how I'm maybe misusing the library. Rather than copying the element and changing the style, it's editing the style of the page in the DOM.

But it's bedtime now, so one for later

**Comment by areon546** [comment]
If you refresh the page it goes back to being black.

**Comment by quii** [comment]
OK, the bug should be fixed now. In addition, I figured it only makes sense in landscape mode (to see the full scoresheet), so you'll only see it in that mode. 

Yes, i guess it would technically be possible to make the portrait mode make the same PDF as landscape, but honestly, what a PITA :)

**Comment by quii** [comment]
@LoganHeasman200 Fixed the miss bug, and Ant said he was happy with it, so good to close?

**Comment by LoganHeasman200** [comment]
Yeah i think that sounds good to me and works well, great job @quii

**Comment by quii** [comment]
tada
