### ISSUE TITLE
Sight markings is buggy, deletes stuff?

### ISSUE THREAD

**Issue by quii** [quii/vue-fast#23]
cc @ruthmoog can you describe steps

**Comment by ruthmoog** [comment]
1. Tap on "Markings" tab
2. Tap the "X" button on any row (e.g. 3rd row (_30_/_Hole 1.4.3.5ish_) )

**Expected**: The tapped row is deleted, and the other rows remain displayed
**Actual**: All rows are deleted! Despair!

![Markings tab](https://github.com/quii/vue-fast/assets/33294286/9fb31760-4f5f-44df-944f-9b73ff49252c)
![Markings tab](https://github.com/quii/vue-fast/assets/33294286/3a0a5237-7202-4b09-a844-ea2ec98eb939)

**Comment by quii** [comment]
Pretty conclusive

**Comment by quii** [comment]
Don't think the feature is worth the effort, just use notes/keep
